name: docgen

defaults:
  run:
    shell: pwsh

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - name: Print out the environment
      run: . .\printEnvironment.ps1

    - name: Download PowerShell packages to run examples with
      run: .\downloadPwshPackages.ps1

    - name: Run tests
      run: |
        Install-Module -Name Pester -Force
        .\runTests.ps1

    - name: Generate the site
      run: .\buildSite.ps1

    - name: Upload the site contents as an artifact
      uses: actions/upload-artifact@v2
      with:
        name: site
        path: .\webroot\

  deploy:
    runs-on: windows-latest
    needs: build
    steps:
    - uses: actions/checkout@v2

    - name: Download the site to the webroot
      uses: actions/download-artifact@v2
      with:
        name: site
        path: .\webroot\

    - name: Deploy the site to Netlify
      uses: nwtgck/actions-netlify@v1.1
      with:
        publish-dir: .\webroot\
        production-branch: main
        github-token: ${{ secrets.GITHUB_TOKEN }}
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
